:scrollbar:
:data-uri:
:toc2:
:numbered:

= OptaPlanner Training Lab Overview

== Introduction

This training will help you become an OptaPlanner expert.
Count how many labs you can complete correctly without cheating :)

=== Prerequisites

* Basic understanding of Java development
* Basic understanding of DRL (drools rule language)

=== Preparation

. Open the http://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html[the reference manual] in your browser.
.. Read the chapter _Introduction_.
.. Read the chapter _Quick start_.
.. Read the table of contents (TOC). Grok the structure of the reference manual.
. Unzip the `optaplanner-training-\*.zip`. This is a different zip than `optaplanner-distribution-\*.zip`.
. Open your favorite IDE (IntelliJ, Eclipse, NetBeans).

=== Troubleshooting

* If you have any trouble running the code in your favorite IDE,
http://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html#runTheExamplesInAnIDE[read this].

ifdef::showscript[]

endif::showscript[]
